### ISSUE TITLE
rename acceleration in cars.json to timeToXXXmph

### ISSUE THREAD

**Issue by kanitw** [vega/vega-datasets#3]

**Comment by jheer** [comment]
Changes like this are likely to break existing visualizations. Avoid unless absolutely necessary.

**Comment by domoritz** [comment]
Agreed. I think units should be in some kind of metadata data structure.

**Comment by kanitw** [comment]
I do not think that this should be in metadata.

The problem is "acceleration" is so confusing as it's more like an inverse of acceleration.   Dom was confused once when we do the practice talk.  I'm creating this issue because I observe other people name this confusing "acceleration" using "timeToXXXMph" and then it totally makes sense  (XXX is replaced with actual number).

We only need to fix a few existing examples to reflect this rename, so I wonder if we should just do that and make our demos less confusing -- both for the UIs and toolkits.

**Comment by randyzwitch** [comment]
Another vote for not changing anything about canonical datasets. `cars.json` is the mtcars dataset from R and other places, right? 

Given the purpose of the example datasets is not enlightenment, but rather just displaying functionality of vega, I wouldn't want to have to think about whether I'm using the right data because the column names are different than I'm used to. I want to look at an [R example}(http://www.statmethods.net/graphs/images/boxplot1.jpg), translate it to Vega, get the same thing back...perfect validation.

Once I'm mentally mapping  "Acceleration" to "timeToXXXMph" and "Displacement" to "engineCubicCentimeters", then the familiarity is lost.

**Comment by kanitw** [comment]
@randyzwitch   I just checked.  This is a cars dataset from ASA SCSG http://stat-computing.org/dataexpo/1983.html, which is different from R’s mtcars.   

Regarding using similar variable names, maybe keeping “acceleration” makes sense.

However, some variables name in the current cars.json still do not match the original data
- `Miles per Gallon` (original = `mpg`)
- `Year` (original = `model.year`)
- We use Titlecase for all variables while the original data use lowercase. 

If we argue for consistency with original dataset, this should be handled as well.  

Also, `origin`'s values is now “A”, “B”, “C” in our dataset, but they were originally 1, 2, 3 where 1= American, 2 = European, 3=Japanese.

**Comment by domoritz** [comment]
At this point, I am used to it.
