### ISSUE TITLE
Flights 3m only has 200k rows

### ISSUE THREAD

**Issue by domoritz** [vega/vega-datasets#607]
https://github.com/vega/vega-datasets/blob/main/data/flights-3m.csv seems to only have 200k rows. 

```
wc -l flights-3m.csv
  231084 flights-3m.csv
```

Added in https://github.com/vega/vega-datasets/commit/1e70098e5c15069314a1be82a37c82c0fbb5f66f by @arvind

**Comment by dsmedia** [comment]
Looks like the count in `flights_200k` may also be off.

```python
from vega_datasets import data

datasets = ['flights_2k', 'flights_5k', 'flights_10k', 'flights_20k', 'flights_200k', 'flights_3m']

for dataset_name in datasets:
    dataset = getattr(data, dataset_name)()
    row_count = len(dataset)
    print(f"{dataset_name}: {row_count} rows")
```

Results:
```
flights_2k: 2000 rows
flights_5k: 5000 rows
flights_10k: 10000 rows
flights_20k: 20000 rows
flights_200k: 231083 rows
flights_3m: 231083 rows
```

We can regenerate 3m rows using [this script](https://gist.github.com/domoritz/894a85c2660d99eb05847770cc5c478f), create a csv from the 3m parquet file [here](https://gist.github.com/domoritz/fd517a3a3a210c24a488e61870e2cf2c) or something else?

**Comment by dsmedia** [comment]
Hi @domoritz, would either of these approaches work for regenerating the full 3m dataset? Let me know if you need any clarification or have another preferred solution in mind.

**Comment by domoritz** [comment]
The 200k is the same as https://square.github.io/crossfilter/ and we should make sure to keep that as close as possible.

The data is from 2001 I think so we will need to download it again it seems like. 

```
D select min(FL_DATE), max(FL_DATE) from "flights-10m.parquet";
┌──────────────┬──────────────┐
│ min(FL_DATE) │ max(FL_DATE) │
│     date     │     date     │
├──────────────┼──────────────┤
│ 2006-01-01   │ 2007-06-30   │
└──────────────┴──────────────┘
```

There is a script to generate the flights data in https://github.com/vega/vega-datasets/blob/main/scripts/flights.js (coming from the commit I mentioned in the original issue). 

Please go ahead. Would be great to fix this.

**Comment by dsmedia** [comment]
I wanted to highlight a small inconsistency in how dates and times seem to be handled in the current flights datasets. Taking the first row of the current fights-3m.csv as an example:

**Current format:**
```csv
date,delay,distance,origin,destination
01010001,14,405,MCI,MDW
```

The date field (01010001) encodes Jan 1, 2001, 00:01 (The year 2001 is fixed for all rows). This appears to differ from the source FAA data:

FlightDate: 2001-01-01
CRSDepTime: 2350 (scheduled departure 23:50)
DepTime: 1.0 (actual departure 00:01)
DepDelay: 11.0 minutes
ArrDelay: 14.0 minutes

This flight actually departed on Jan 2 (next day) at 00:01, 11 minutes after its scheduled time of 23:50 on Jan 1. The current dataset's date encoding doesn't seem to capture this overnight boundary crossing.

After reviewing how this dataset is typically used for flight delay analysis, I believe we should encode the scheduled departure time (CRSDepTime) rather than actual departure time. This aligns with the common use case of analyzing delays based on scheduled flight times, with the delay field (using arrival delay) capturing the actual impact on travelers.

The good news is that, since the 2001 FAA source data is still available, we'll be able to regenerate the dataset from the same source as the original, ensuring consistency with the historical data while potentially addressing these data consistency issues.

**Comment by domoritz** [comment]
Not sure who is using the 3m dataset anyway. I'm happy to change that one. The other ones we want to be more careful with.

**Comment by domoritz** [comment]
I think there is value in looking at actual departure time rather than scheduled. It would be great if we could fix the date for the ones where we didn't have it right.  Same for the 3m one.
